CREATE TABLE `goods` (
  `goodsId` int(255) NOT NULL AUTO_INCREMENT,
  `goodsTitle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `goodsTag` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `goodsPrice` float(10,2) DEFAULT NULL,
  `goodsStock` int(255) DEFAULT NULL,
  `imageList` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `goodsStatus` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `goodsInfo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `categoryId` int(255) DEFAULT NULL,
  PRIMARY KEY (`goodsId`),
  KEY `goodsId` (`goodsId`),
  KEY `goodsId_2` (`goodsId`),
  KEY `goods_ibfk_1` (`categoryId`),
  KEY `goodsId_3` (`goodsId`),
  KEY `goodsId_4` (`goodsId`),
  KEY `goodsId_5` (`goodsId`),
  KEY `goodsId_6` (`goodsId`),
  KEY `goodsId_7` (`goodsId`),
  KEY `goodsId_8` (`goodsId`),
  KEY `goodsId_9` (`goodsId`),
  KEY `goodsId_10` (`goodsId`),
  KEY `goodsId_11` (`goodsId`),
  KEY `goodsId_12` (`goodsId`),
  KEY `goodsId_13` (`goodsId`),
  KEY `goodsId_14` (`goodsId`),
  KEY `goodsId_15` (`goodsId`),
  KEY `goodsId_16` (`goodsId`),
  KEY `goodsId_17` (`goodsId`),
  CONSTRAINT `goods_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `category` (`categoryid`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;