CREATE TABLE `user` (
  `userId` int(255) NOT NULL AUTO_INCREMENT,
  `phone` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `username` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `identityNo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `userAvatar` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT 'https://s2.loli.net/2022/04/15/v8HRVkgOYN3qtmB.jpg',
  PRIMARY KEY (`userId`) USING BTREE,
  KEY `userId` (`userId`),
  KEY `userId_2` (`userId`),
  KEY `userId_3` (`userId`),
  KEY `userId_4` (`userId`),
  KEY `userId_5` (`userId`),
  KEY `userId_6` (`userId`),
  KEY `userId_7` (`userId`),
  KEY `userId_8` (`userId`),
  KEY `userId_9` (`userId`),
  KEY `userId_10` (`userId`),
  KEY `userId_11` (`userId`),
  KEY `userId_12` (`userId`),
  KEY `userId_13` (`userId`),
  KEY `userId_14` (`userId`),
  KEY `userId_15` (`userId`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;